### ISSUE TITLE
php pyrus.phar make failing

### ISSUE THREAD

**Issue by jmcastagnetto** [pyrus/Pyrus#1]
Just downloaded PEAR2_Pyrus 2.0.0a2 from pear2.php.net and generates an exception when trying to make a package.xml for [Math_Trigonometry](https://github.com/jmcastagnetto/Math_Trigonometry) using:
- php ~/Downloads/pyrus.phar make

I got the devel tools installed.

Here is a stack trace using xdebug:

Pyrus version 2.0.0a2 SHA-1: CA3946A5C2C7DE7CD6ED89CAC7CCC06606E006D3
Using PEAR installation found at /home/jesus/devel/pear2packages
Creating package.xml...PHP PEAR2\Pyrus\PackageFile\Exception:  Invalid package.xml, does not validate against schema in phar:///home/jesus/Downloads/pyrus.phar/PEAR2_Pyrus-2.0.0a2/php/PEAR2/Pyrus/PackageFile/v2/Validator.php on line 98
PHP Stack trace:
PHP   1. {main}() /home/jesus/Downloads/pyrus.phar:0
PHP   2. PEAR2\Pyrus\ScriptFrontend\Commands->run($args = array (0 => 'make')) /home/jesus/Downloads/pyrus.phar:52
PHP   3. PEAR2\Pyrus\Developer\PackageFile\Commands->makePackageXml($frontend = class PEAR2\Pyrus\ScriptFrontend\Commands { public $commands = array (); protected $verbose = '1'; protected $term = array ('bold' => '\033[1m', 'normal' => '\033[m') }, $args = array ('packagename' => NULL, 'channel' => NULL, 'dir' => NULL), $options = array ('nocompatible' => NULL, 'packagexmlsetup' => NULL, 'scanoptions' => NULL, 'package' => NULL, 'stub' => NULL, 'extrasetup' => NULL, 'help' => NULL)) phar:///home/jesus/Downloads/pyrus.phar/PEAR2_Pyrus-2.0.0a2/php/PEAR2/Pyrus/ScriptFrontend/Commands.php:288
PHP   4. PEAR2\Pyrus\Developer\PackageFile\PEAR2SVN->__construct($path = '/home/jesus/devel/git/github/Math_Trigonometry', $packagename = NULL, $channel = 'pear2.php.net', $return = FALSE, $fullpathsused = TRUE, $doCompatible = TRUE, $scanoptions = array ()) /home/jesus/.pear/php/PEAR2/Pyrus/Developer/PackageFile/Commands.php:52
PHP   5. PEAR2\Pyrus\Developer\PackageFile\PEAR2SVN->validate() /home/jesus/.pear/php/PEAR2/Pyrus/Developer/PackageFile/PEAR2SVN.php:101
PHP   6. PEAR2\Pyrus\PackageFile\v2\Validator->validate($pf = class PEAR2\Pyrus\Package { protected $internal = class PEAR2\Pyrus\Package\Xml { protected $archive = '/home/jesus/devel/git/github/Math_Trigonometry/package.xml'; protected $packagefile = class PEAR2\Pyrus\PackageFile { ... }; protected $from = ... }; protected $from = NULL; protected $saveAsPackage2_xml = FALSE }, $state = _uninitialized_) /home/jesus/.pear/php/PEAR2/Pyrus/Developer/PackageFile/PEAR2SVN.php:419
PEAR2\Pyrus\PackageFile\Exception: Invalid package.xml, does not validate against schema
 PEAR2\Pyrus\PackageFile\Exception: Line 3: Element '{http://pear.php.net/dtd/package-2.1}channel': This element is not expected. Expected is ( {http://pear.php.net/dtd/package-2.1}name ).

**Comment by indeyets** [comment]
@jmcastagnetto look at the last lines — everything is there. your package.xml is invalid and Pyrus cares about that much more than old pear command

**Comment by saltybeagle** [comment]
Aha, the package.xml file isn't present. Looks like that error needs to be much clearer.

Ususally pyrus starts with something and the 'make' command updates it. The skeleton generator can create a package.xml for you to start with. I suppose we could invoke the skeleton generator if there's no package.xml present. What do you think?

**Comment by saltybeagle** [comment]
Aha, actually it looks like the pyrus dev tools will create a package.xml if you have everything in place.
`pyrus help make` has all the details, but basically you need your README, CREDITS, and RELEASE-0.1.0 files in place so pyrus knows the required details about what package you're building and then `pyrus make Math_Trigonometry` should work.

**Comment by jmcastagnetto** [comment]
OIC, I tried on my netbook and it did work. Also I noticed that my CREDITS files had a utf-8 BOM.

I was being lazy and trying to use pyrus to get a base package.xml with the new format that I could later complete/modify. Now I have a starting point to mangle it :-)

Domo Arigato
