### ISSUE TITLE
Error installing packages 

### ISSUE THREAD

**Issue by Konafets** [pyrus/Pyrus#100]
Installing packages with 
$ sudo php pyrus.phar install -f PEAR2_Pyrus
gives me strange errors:

Using PEAR installation found at /usr/lib/php
Downloading pear2.php.net/PEAR2_Pyrus
Mime-type: text/plain; charset=UTF-8
Downloading pear2.php.net/PEAR2_Autoload=============================================================>] 100% (8419/8419 kb)
Mime-type: application/x-gzip
Downloading pear2.php.net/PEAR2_Exception============================================================>] 100% (24/24 kb)
Mime-type: application/x-gzip
Downloading pear2.php.net/PEAR2_MultiErrors==========================================================>] 100% ( 6/ 6 kb)
Mime-type: application/x-gzip
Downloading pear2.php.net/PEAR2_HTTP_Request=========================================================>] 100% ( 5/ 5 kb)
Mime-type: application/x-gzip
Downloading pear2.php.net/PEAR2_Console_CommandLine==================================================>] 100% (45/45 kb)
Mime-type: application/x-gzip
[====================================================================================================>] 100% (39/39 kb)
Warning: copy(/opt/local/bin/ps4pdf): failed to open stream: No such file or directory in phar:///opt/local/bin/pyrus.phar/Pyrus-2.0.0a4/php/Pyrus/Filesystem.php on line 122

Call Stack:
    0.2170    2121648   1. {main}() /opt/local/bin/pyrus.phar:0
    0.2649    4392352   2. Pyrus\ScriptFrontend\Commands->run() /opt/local/bin/pyrus.phar:68
   74.1654    8325496   3. Pyrus\ScriptFrontend\Commands->install() phar:///opt/local/bin/pyrus.phar/Pyrus-2.0.0a4/php/Pyrus/ScriptFrontend/Commands.php:309
   74.1908   10517856   4. Pyrus\Installer::commit() phar:///opt/local/bin/pyrus.phar/Pyrus-2.0.0a4/php/Pyrus/ScriptFrontend/Commands.php:559
   88.4519   32531208   5. Pyrus\Installer->install() phar:///opt/local/bin/pyrus.phar/Pyrus-2.0.0a4/php/Pyrus/Installer.php:328
   89.4399   31768528   6. Pyrus\AtomicFileTransaction::getTransactionObject() phar:///opt/local/bin/pyrus.phar/Pyrus-2.0.0a4/php/Pyrus/Installer.php:480
   89.4399   31768528   7. Pyrus\AtomicFileTransaction\Manager->getTransaction() phar:///opt/local/bin/pyrus.phar/Pyrus-2.0.0a4/php/Pyrus/AtomicFileTransaction.php:70
   89.4400   31769512   8. Pyrus\AtomicFileTransaction\Transaction->__construct() phar:///opt/local/bin/pyrus.phar/Pyrus-2.0.0a4/php/Pyrus/AtomicFileTransaction/Manager.php:67
   89.4400   31769752   9. Pyrus\AtomicFileTransaction\Transaction->begin() phar:///opt/local/bin/pyrus.phar/Pyrus-2.0.0a4/php/Pyrus/AtomicFileTransaction/Transaction.php:37
   89.4400   31769752  10. Pyrus\AtomicFileTransaction\Transaction\TwoStage->begin() phar:///opt/local/bin/pyrus.phar/Pyrus-2.0.0a4/php/Pyrus/AtomicFileTransaction/Transaction.php:60
   89.4401   31769752  11. Pyrus\AtomicFileTransaction\Transaction\Base->begin() phar:///opt/local/bin/pyrus.phar/Pyrus-2.0.0a4/php/Pyrus/AtomicFileTransaction/Transaction/TwoStage.php:49
   89.4406   31769800  12. Pyrus\Filesystem::copyDir() phar:///opt/local/bin/pyrus.phar/Pyrus-2.0.0a4/php/Pyrus/AtomicFileTransaction/Transaction/Base.php:104
   94.9806   32029656  13. copy() phar:///opt/local/bin/pyrus.phar/Pyrus-2.0.0a4/php/Pyrus/Filesystem.php:122

Pyrus\Installer\Exception: Installation failed
 Pyrus\AtomicFileTransaction\MultiException: Unable to begin transaction
  Pyrus\IOException: Unable to copy directory, failed to copy the file
   Pyrus\AtomicFileTransaction\RuntimeException: Cannot rollback - not in a transaction

I don't know why pyrus wants copy file /opt/local/bin/ps4pdf. Maybe someone can enlighten me :-)

**Comment by saltybeagle** [comment]
Hi Stefano, this is an unfortunate known bug. All the details are here: #3
