### ISSUE TITLE
generate-ext gives warnings

### ISSUE THREAD

**Issue by saltybeagle** [pyrus/Pyrus#12]
$ pyrus generate-ext xhprof
Using PEAR installation found at /Users/bbieber/pear
PHP Warning:  file_get_contents(/config.m4): failed to open stream: No such file or directory in /Users/bbieber/Documents/workspace/PEAR2_Pyrus_Developer/src/PEAR2/Pyrus/Developer/PackageFile/Commands.php on line 795
...

**Comment by helgi** [comment]
FIXED!
