### ISSUE TITLE
 Pear1 - could not create Dependency lock file

### ISSUE THREAD

**Issue by cweiske** [pyrus/Pyrus#29]
## Description:

run phpt on all\Pyrus\tests\Registry\Pear1 directory.
## Test script:

php scripts/pyrus run-phpt tests\Registry\Pear1\package\basic\basic.phpt
## Expected result:

=== DONE ===
## Actual result:

Could not create Dependency lock file exception

**Comment by cweiske** [comment]
Patch available at http://pear.php.net/bugs/bug.php?id=17869&edit=12&patch=Path_patch&revision=latest

**Comment by fpoirotte** [comment]
The patch has been applied in eb58d230 by @saltybeagle.
