### ISSUE TITLE
\PEAR2\Pyrus\Package exception

### ISSUE THREAD

**Issue by cweiske** [pyrus/Pyrus#30]
## Description:

When creating a new instance of a package that is all ready in the rgistry a exception occures.
## Test script:

<?php
require_once 'PEAR2\Autoload.php';
\PEAR2\Pyrus\Config::setCurrent('d:/pear/testRepo');

// The will work like a charm
$pkg = new \PEAR2\Pyrus\Package('pear2.php.net/PEAR2_Pyrus');

// This will throw a 'PEAR2\Pyrus\Package\InstalledException'
$pkg = new \PEAR2\Pyrus\Package('pear2.php.net/PEAR2_Pyrus-2.0.0a1');
## Expected result:
- No exception (since the Package object can also be used to retrieve information).
## Actual result:

Fatal error: Uncaught exception 'PEAR2\Pyrus\Package\InstalledException' with message 'channel://pear2.php.net/PEAR2_Pyrus-2.0.0a1 is already installed and is newer than detected release version 2.0.0a1' in D:\pear\repo\php\PEAR2\Pyrus\Package\Remote.php:282
Stack trace:
#0 D:\pear\repo\php\PEAR2\Pyrus\Package\Remote.php(47): PEAR2\Pyrus\Package\Remote->fromString('pear2.php.net/P...')
#1 D:\pear\repo\php\PEAR2\Pyrus\Package.php(55): PEAR2\Pyrus\Package\Remote->__construct('pear2.php.net/P...', Object(PEAR2\Pyrus\Package))
#2 D:\pear\packages\PackageManager\tests\u.php(7): PEAR2\Pyrus\Package->__construct('pear2.php.net/P...')
#3 {main}

  thrown in D:\pear\repo\php\PEAR2\Pyrus\Package\Remote.php on line 282

**Comment by cweiske** [comment]
saltybeagle (Brett Bieber)
Hmm, I think in this case the exception is to be expected.

To retrieve information about remote packages, pass $forceremote = true to Package::__construct so it won't look at the local registry before comparing against remote packages.

**Comment by cweiske** [comment]
boekkooi (Warnar Boekkooi)
Okee so what your saying is don't use Package for getting information about a package that's allready installed? but use Registry::package and Registry::exists?

**Comment by fpoirotte** [comment]
Does this mean this ticket is bogus then?

**Comment by till** [comment]
@cweiske Ping. Close it, if it's bogus.

**Comment by cweiske** [comment]
I don't really like the current behavior, but ok. There is an alternative we can use.
