### ISSUE TITLE
Pyrus Install - No channel.xml

### ISSUE THREAD

**Issue by mfonda** [pyrus/Pyrus#36]
(Bug migrated from pearweb bug #17588)
## Description:

\PEAR2\Pyrus\Config::singleton('d:\pear\testRepo') throws a 'Fatal error: Uncaught exception 'PEAR2\Pyrus\ChannelFile\Exception' with message 'Invalid channel.xml' in D:\pear\repo\php\PEAR2\Pyrus\ChannelFile\Parser\v1.php'.

It looks like when i create a new registry with the following command (this is not my main registry):
php pyrus.phar D:\pear\testRepo install PEAR2_autoload
No channel.xml is made.
## Test script:

To reproduce:
- Create a second registry:
  php pyrus.phar D:\pear\testRepo install PEAR2_autoload
- Run code:
  <?php
  require_once 'PEAR2\Autoload.php';
  $config = \PEAR2\Pyrus\Config::singleton('d:\pear\testRepo');
## Expected result:

A \PEAR2\Pyrus\Config instance.

After runnings:
php pyrus.phar D:\pear\testRepo list-channels
All works like a charm.
## Actual result:

Fatal error: Uncaught exception 'PEAR2\Pyrus\ChannelFile\Exception' with message 'Invalid channel.xml' in D:\pear\repo\php\PEAR2\Pyrus\ChannelFile\Parser\v1.php:34
Stack trace:
#0 D:\pear\repo\php\PEAR2\Pyrus\ChannelRegistry\Base.php(295): PEAR2\Pyrus\ChannelFile\Parser\v1->parse('D:\pear\repo\ph...', true)
#1 D:\pear\repo\php\PEAR2\Pyrus\ChannelRegistry\Base.php(265): PEAR2\Pyrus\ChannelRegistry\Base->getDefaultChannel('pear.php.net')
#2 D:\pear\repo\php\PEAR2\Pyrus\ChannelRegistry\Base.php(304): PEAR2\Pyrus\ChannelRegistry\Base->getPearChannel()
#3 D:\pear\repo\php\PEAR2\Pyrus\ChannelRegistry\Sqlite3.php(119): PEAR2\Pyrus\ChannelRegistry\Base->initDefaultChannels()
#4 D:\pear\repo\php\PEAR2\Pyrus\ChannelRegistry\Sqlite3.php(55): PEAR2\Pyrus\ChannelRegistry\Sqlite3->_init('D:\pear\testrep...', false)
#5 D:\pear\repo\php\PEAR2\Pyrus\ChannelRegistry.php(61): PEAR2\Pyrus\ChannelRegistry\Sqlite3->__construct('D:\pear\testrep...', false)
#6 D:\pear\repo\php\PEAR2\Pyrus\Registry.php(116): PEAR2\Pyrus\ChannelRegistry->__constru in D:\pear\repo\php\PEAR2\Pyrus\Config.php on line 515
## Additonal Commnet

There is one change i made in pearconfig.xml: <preferred_state>alpha</preferred_state>

When changing the back to 'stable' and retrying the same exception occures.

**Comment by till** [comment]
As far as I can tell (by testing), this is fixed in alpha4/master.
