### ISSUE TITLE
Pyrus does not respect XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by mfonda** [pyrus/Pyrus#37]
(migrated from pearweb request #18381)
## Description:

When Pyrus initializes, it creates an  unsolicited directory $HOME/.pear/ instead of $HOME/.config/pear/
There's also no way to override that setting.

Home directory spamming was an established practice in the 90s. Meanwhile there is an agreed standard on where to put non-critical and non-system configuration files. $XDG_CONFIG_HOME or at the very least defaulting to $HOME/.config/

http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

Btw, its use is equivalent to %APPDATA% on Windows if I'm not mistaken.

**Comment by saltybeagle** [comment]
Correction, home directory spamming _is_ an established practice.

I'd be happy to accept any patches on this issue, but I do not see it as a priority.
