### ISSUE TITLE
Automatic creation of bundles (package + dependencies)

### ISSUE THREAD

**Issue by mfonda** [pyrus/Pyrus#40]
(Migrated from pearweb request #11101)
## Description:

It would be great if Pyrus could automatically create a bundle of a package. This would include all direct and indirect dependencies.

I am doing this by hand, because such a bundle has some advantages:
- Speed: I have an application with 40 dependencies (direct and indirect), install/upgrade with bundle takes a few seconds, with a normal package multiple minutes.
- Flexibility: Installation is possible everywhere and everytime. For example on servers without direct internet access and even if pear.php.net is down.
- Security: You can be sure that you have all dependencies (PHPUnit2-problem) and that they are the same on every installation.

**Comment by cellog** [comment]
I have great news: pyrus was specifically designed to make this possible.  Check out the script that builds pyrus.phar, it pulls in several dependencies and bundles them.  This way, it can access them inside the phar.  Currently installation of the whole bundle is not yet implemented, but could be done with some thought

**Comment by saltybeagle** [comment]
@berdir, FYI, @cellog responded with some additional info that might be helpful.
