### ISSUE TITLE
Pyrus should expand relative paths

### ISSUE THREAD

**Issue by mfonda** [pyrus/Pyrus#43]
When a pyrus command is passed a relative path, this path does not necessarily necessarily get expanded.

For example,

```
$ cd /home/mfonda/pyrus
$ php pyrus.phar mypear ./
```

I would expect this to set `my_pear_path` to `/home/mfonda/pyrus`, but it literally gets set to `./`

**Comment by saltybeagle** [comment]
This is actually a really handy thing to have. Just like in PHP you can set your include path to "."  you could set pyrus to ./vendor to handle vendor dependencies inside the root of each project.

**Comment by mfonda** [comment]
Good point, that could be very useful.
