### ISSUE TITLE
fails to run when detect_unicode is enabled

### ISSUE THREAD

**Issue by gauthierm** [pyrus/Pyrus#5]
[avb@www ~]$ uname -a
FreeBSD www 8.2-RELEASE FreeBSD 8.2-RELEASE #0: Thu Feb 17 02:41:51 UTC 2011 
  root@mason.cse.buffalo.edu:/usr/obj/usr/src/sys/GENERIC  amd64
[avb@www ~]$ php -v
PHP 5.3.5 (cli) (built: Feb 21 2011 14:33:13)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
[avb@www ~]$ php -ddetect_unicode=1 pyrus.phar
??\sP?[avb@www ~]$

Relevant bug: http://bugs.php.net/52348

We can detect this in 5.3.4+ using the constant ZEND_MULTIBYTE + ini_get('detect_unicode')

Prior versions can use key_exists("detect_unicode", ini_get_all()) + ini_get('detect_unicode')

**Comment by gauthierm** [comment]
Hmm, looks like it's actually a core PHP bug: http://bugs.php.net/bug.php?id=42396

**Comment by saltybeagle** [comment]
If we can detect it before it fails, that'd be great.

**Comment by saltybeagle** [comment]
I've added a check to the stub so if users chmod +x pyrus.phar it should run correctly now. Not much more we can do.
