### ISSUE TITLE
Allow download of packages rather than just install

### ISSUE THREAD

**Issue by mattfarina** [pyrus/Pyrus#63]
Say I want to download wordpress to the directory I'm currently in. It would be nice to be able to do something like:

```
$ php pyrus.phar get wordpress
```

This would download wordpress and expand it for me. Having a second form of package like this would be very useful.

**Comment by saltybeagle** [comment]
I think that's a great idea. It's a feature the pear installer already supports, and pyrus is missing.

**Comment by helgi** [comment]
pyrus has a download feature, see "pyrus help download" but it does not expand the downloaded archive, however - I am not a fan of that command and think it should be a switch on the install command.

**Comment by saltybeagle** [comment]
Closing this issue since the download command is already available.
