### ISSUE TITLE
make pyrus a command line utility

### ISSUE THREAD

**Issue by mattfarina** [pyrus/Pyrus#64]
It would be nice to be able to do something like:

```
$ pyrus install foo
```

That means no php or .phar involved. Make it a true command line utility.

**Comment by saltybeagle** [comment]
A wrapper script could certainly be provided, or installed with a helper command.

You can also chmod +x the pyrus.phar and execute it directly at the CLI.

**Comment by mattfarina** [comment]
The idea would be for it to exist someplace like /usr/bin so it's in the users path. That way it can be executed from anywhere like a regular command line app.

**Comment by helgi** [comment]
The idea was to create a wrapper package or a similar solution that can compliment pyrus and provide that functionality. Someone just has to step up and do it.

I could see it being a part of a install.sh or go-pyrus.php or some and it would install all of those shell / bat scripts like PEAR has and then drop the Pyrus.phar file in the appropriate place.

Anyone see flaws with that approach?

**Comment by till** [comment]
@mattfarina: Do you feel like contributing this?

**Comment by mattfarina** [comment]
I had initially thought about writing something like this. But, with the current demands on my time I just can't commit to writing this. It's too low on my priority list.

**Comment by till** [comment]
This seems to work:

```
#!/usr/bin/env php /usr/local/Cellar/php54/5.4.6/bin/pyrus.phar
```

**Comment by till** [comment]
Closing this — IMHO, we should work on getting pyrus into package managers sooner or later and then they can take care of this.
