### ISSUE TITLE
Handle package bundles

### ISSUE THREAD

**Issue by mattfarina** [pyrus/Pyrus#67]
Say for instance I have an app called foo. Within that app I wanted to have a bunch of packages in a local directory. It would be nice to be able to define a file bundle.xml that holds all the name and versions of the bundles to install. Then, from within the apps directory structure I could do:

  $ pyrus bundle install

And it would make sure all the packages defined in bundle.xml were installed to/updated in the proper place.

**Comment by saltybeagle** [comment]
See https://github.com/pyrus/Pyrus_VendorCommands which does what you're asking for, by examining the package.xml

**Comment by mattfarina** [comment]
Is this part of Pyrus proper in the phar that's downloaded? Is there any documentation on how to use it?

**Comment by saltybeagle** [comment]
Right now it's not included by default, and is available as a plugin. I would like to see it included by default, of course. But it'd be great to get some more feedback and flesh out how all the dependencies should be managed within an app.

**Comment by saltybeagle** [comment]
Oh, and there's currently no documentation outside of the command help text, source here: https://github.com/pyrus/Pyrus_VendorCommands/blob/master/customcommand/commands.xml

**Comment by till** [comment]
Apparently not an issue because available.
