### ISSUE TITLE
pyrus package does not support package.xml supported by 1.x serie

### ISSUE THREAD

**Issue by pierrejoye** [pyrus/Pyrus#70]
hi,

Trying to play with pyrus.phar directly (a3) for pecl, I noticed that many package.xml do not work anymore. That's sadly a no go to use pyrus as we do need to support existing format.

For an example, see the last zip release on pecl

http://pecl.php.net/get/zip-1.10.2.tgz

**Comment by cweiske** [comment]
PEAR did not validate the package.xml against the DTD, which is what Pyrus does now.

Technically, the package.xml files are invalid.

**Comment by pierrejoye** [comment]
I understand that but there are two problems here:
- It is not backward compatible, making pyrus unsuable for many packages released prior to pyrus (aka using pear 1.x)
- It does not tell in any way where it fails, and I fail to see what is wrong, for example

**Comment by pierrejoye** [comment]
So it seems that it is about the changelog part. 

Where:

``` xml
<release>
   <date>2009-07-20</date>
   <version>
    <release>1.10.1</release>
    <api>2.0.0</api>
   </version>
   <stability>
    <release>stable</release>
    <api>stable</api>
   </stability>
   <license uri="http://www.php.net/license">PHP License</license>
   <notes>
- #48763, ZipArchive produces corrupted archive (dani dot church at gmail dot com)
- Fixed regression in the overwrite mode
- Fixed binary mode with FCGI on Windows
   </notes>
  </release>
```

should instead be:

``` xml
<release>
   <version>
    <release>1.10.1</release>
    <api>2.0.0</api>
   </version>
   <stability>
    <release>stable</release>
    <api>stable</api>
   </stability>
   <date>2009-07-20</date>
   <license uri="http://www.php.net/license">PHP License</license>
   <notes>
- #48763, ZipArchive produces corrupted archive (dani dot church at gmail dot com)
- Fixed regression in the overwrite mode
- Fixed binary mode with FCGI on Windows
   </notes>
  </release>
```

I know it is a limitation of the validation (afair) but this is something awkward. Both XML are perfectly valid, there is no point to consider the 1st version as invalid and should not be. I was arguing about that already years ago with Greg when he was trying to enforce that.

**Comment by saltybeagle** [comment]
There's no real argument, someone just needs to modify the .xsd to be more flexible. This has been done already to some degree, see ab3775cb12c42a70bd6cf08f04088e3a03e8e5d0 

You're just finding more instances where you would prefer the schema be more flexible.

**Comment by pierrejoye** [comment]
It is more about XML validity that schema per se. I discussed that with Brett before posting this bug. The real confusion here is that the order is different in both parts of the package.xml.

New releases can be easily fixed, my main concern here is BC with older releases. I was also suggesting to add a --force mode, or to call it better, --no-xsd-validation mode. That should do the trick.

**Comment by pierrejoye** [comment]
Arf :) Read cweiske instead of saltybeagle :)

**Comment by helgi** [comment]
This is a big problem - People seem to have randomly hand edited the XML files. Seems we are pretty good where people have used PFM or a similar automated solution.

Another place I noticed failing quite often is anything gopal maintains :) See APC for example, where <active> in maintainers is suppose to be boolean but people seem to be putting their username for some reason.

I want to see us improve the error messages and exactly because of PECL I want to add a skip like option, such as the one Pierre mentioned. Not technically a force but makes it behave like PEAR... I need it for selfish reasons but I may contribute it back if people like it ;-)

Making the XSD more flexible would also help us a lot, I never saw the point of enforcing a particular order, tho it can be nice when reviewing the XML files but that is so much rarer than people writing incorrect order but still a fairly valid file.

**Comment by CloCkWeRX** [comment]
Is the very fact we're using xsd, and the fact it implies sequences in tags the wrong choice for us? Schematron for instance relies on xpaths being present - if there's extra crap; or it is in the wrong order, it doesn't care; so long as the rules are present.

http://dret.net/lectures/xml-fall08/schemalanguages touches on some of the offerings available.

**Comment by saltybeagle** [comment]
This is not something I'm going to target fixing. The package.xml for those packages are not valid with the current package schema file.

I'd be happy to accept improvements to the package-2.0.xsd schema files if anyone is brave enough to try.
