### ISSUE TITLE
Ignore VCS files during `pyrus.phar make`

### ISSUE THREAD

**Issue by fpoirotte** [pyrus/Pyrus#72]
When running `pyrus.phar make ...`, it will create/update a package.xml file by recursively scanning directories from a standard layout.
While doing so, it picks up VCS related files (in my case, the ".git" directory from a git submodule).

I think such directories should be ignored by default (maybe with an option to override the patterns in case you want to include some of those files).
For example, most tasks in Phing will ignore the following directories by default:
- .git
- .svn
- CVS
- .bzr
- .hg

The same could also apply to files (to prevent files such as "foo.php.bak", "foo.php~", ".foobar.swp", etc. from being added to the package).

**Comment by saltybeagle** [comment]
This feature request should actually go with Pyrus_Developer. Let me move it there first.

**Comment by saltybeagle** [comment]
Moved to pyrus/Pyrus_Developer#9
