### ISSUE TITLE
Allow for dots in package names

### ISSUE THREAD

**Issue by pmjones** [pyrus/Pyrus#75]
Currently, naming a package "Vendor_Name.Package_Name" is disallowed when creating a package. Can we make it so that dots are valid separators in a package name?

**Comment by pmjones** [comment]
Could it be as simple as changing the regex at ...

https://github.com/pyrus/Pyrus/blob/master/src/Pyrus/Validate.php#L38

... to something like '[A-Za-z][a-zA-Z0-9_.]+' ?

**Comment by harikt** [comment]
Any issues regarding this ? Or do we need to send a PR ?

**Comment by saltybeagle** [comment]
I can't think of any issues that change would cause. A PR would be great.

**Comment by till** [comment]
PR and a small test would be much appreciated.

**Comment by harikt** [comment]
How can I run test first ?
I tried 

```
 $ phpunit tests/AllTests.php
```

Getting a bunch of errors :( . Never used phpt though :( .

**Comment by saltybeagle** [comment]
You can run all the tests with:

`pyrus run-phpt -r tests` or `pear run-tests -r tests`

I believe PHPUnit can run .phpts but I've no experience with that.

**Comment by harikt** [comment]
```
$ cat run-tests.log 
TOTAL TIME: 30:02
1 PASSED TESTS
1 SKIPPED TESTS
2 FAILED TESTS:
/media/Linux/Pyrus/tests/Validate/validateversion.failure.alpha.2.0.0.phpt
/media/Linux/Pyrus/tests/Validate/validateversion.validsnapshot.phpt
```

Wondering Is that ok with the failure for validate ?

**Comment by saltybeagle** [comment]
Hmm. Only 2 failures is fantastic — that there were only 4 tests is a problem. :-)

There should be around 726 tests.

**Comment by saltybeagle** [comment]
Here's what I get:

```
TOTAL TIME: 03:28
711 PASSED TESTS
7 SKIPPED TESTS
8 FAILED TESTS:
/Users/bbieber/Documents/workspace/Pyrus/tests/AtomicFileTransaction/AtomicFileTransactionClass/createOrOpenPath/createoropenpath.fail.fp.stream.empty.phpt
/Users/bbieber/Documents/workspace/Pyrus/tests/AtomicFileTransaction/TransactionClass/createOrOpenPath/createoropenpath.fail.fp.stream.empty.phpt
/Users/bbieber/Documents/workspace/Pyrus/tests/Channel/creation.phpt
/Users/bbieber/Documents/workspace/Pyrus/tests/Config/setCascadingRegistries/basic2.phpt
/Users/bbieber/Documents/workspace/Pyrus/tests/Registry/Pear1/getdependentpackages/getdependentpackages.basic.phpt
/Users/bbieber/Documents/workspace/Pyrus/tests/ScriptFrontend/Commands/findpear1.phpt
/Users/bbieber/Documents/workspace/Pyrus/tests/ScriptFrontend/Commands/findpear2.phpt
/Users/bbieber/Documents/workspace/Pyrus/tests/ScriptFrontend/Commands/help.phpt
```

**Comment by harikt** [comment]
By the way I run only for Validate, for it seems only change for Validate is needed .

```
 $ php pyrus.phar run-phpt -r tests/Validate
```

But failures are not good , is this only on master ?

**Comment by harikt** [comment]
hm , sorry it seems something went wrong . Forgot about the error when I run it . Now I am getting 36 success ones for Validate .

**Comment by saltybeagle** [comment]
Oh, I thought you were still trying to understand how to run the tests.

Yes, if you've got a new test, and there are now failures — that's a problem. 

It looks like there's currently 36 tests in the Validate dir:

```
$ php pyrus.phar run-phpt -r tests/Validate
...
TOTAL TIME: 00:02
36 PASSED TESTS
0 SKIPPED TESTS
0 FAILED TESTS
```

**Comment by harikt** [comment]
Sorry this seems hard for me :( . I am stepping out . 
Things I did 
1 ) Created a channel server with pirum 
2 ) Changed the validation as @pmjones mentioned 
3 ) To test we need to create a package . As I have made the necessary changes , I cannot use the pyrus.phar I guess . Seems I want to generate again the phar file . 
I am still not sure how to make it .

So sorry leaving for the time :( . If someone can help if its easy .

**Comment by saltybeagle** [comment]
I think we're good to go. Thanks @harikt

**Comment by harikt** [comment]
Wow great @saltybeagle . The credit goes to @pmjones . 
Yes I have tested it some days back when you merged the commit. 
But I was not successful creating the phar file . So you guys will be updating the `phar` soon ? May be its easy for you :-) . @pmjones  What about introducing @pear packages in the coming release if `phar` is available ?

**Comment by saltybeagle** [comment]
I'm working on getting a new pyrus.phar out.... I was hoping to fix one more bug but it's not going as well as I'd hoped.

**Comment by harikt** [comment]
Looking forward for the new `phar` as the old one seems released 6 months back . So may be lots of Bug fixes already here :-)
