### ISSUE TITLE
Build instructions appear outdated / regression from namespace removal?

### ISSUE THREAD

**Issue by CloCkWeRX** [pyrus/Pyrus#76]
clockwerx@sgrv1:~$ git clone https://github.com/pyrus/Pyrus.git
clockwerx@sgrv1:~$ git clone https://github.com/pyrus/Pyrus_Developer.git
clockwerx@sgrv1:~$ cd Pyrus
clockwerx@sgrv1:~/Pyrus$ php scripts/pyrus upgrade -p ../Pyrus_Developer/package.xml
Using PEAR installation found at /home/clockwerx/pear2
Downloading pyrus.net/Pyrus_Developer
Installed pyrus.net/Pyrus_Developer-0.5.0
clockwerx@sgrv1:~/Pyrus$ php -dphar.readonly=0 scripts/pyrus make -pphar,tar,tgz,zip
Using PEAR installation found at /home/clockwerx/pear2
Class PEAR2\Pyrus\Developer\PackageFile\Commands could not be loaded from PEAR2/Pyrus/Developer/PackageFile/Commands.php, file does not exist (registered paths="/home/clockwerx/Pyrus/vendor/php:/home/clockwerx/Pyrus/src") [PEAR2_Autoload-0.2.4]

Probably 5f65633decb69468cc1cf42beb4ff8b27561e200

**Comment by CloCkWeRX** [comment]
Oops, https://github.com/pyrus/Pyrus_Developer/commit/5f65633decb69468cc1cf42beb4ff8b27561e200

**Comment by till** [comment]
Likely related to #77

**Comment by saltybeagle** [comment]
This issue has been fixed. The package.xml for Pyrus_Developer simply needed to be updated.
