### ISSUE TITLE
Support installation of composer packages

### ISSUE THREAD

**Issue by CloCkWeRX** [pyrus/Pyrus#81]
Packagist/Composer have arrived; and while relatively new they have a bit more momentum than pear2 by itself. PEARHub is out equivalent, and while it's not bad it isn't getting the same kind of press either :)

Composer can already deal with a pear package and install that; we should look to provide the same support in reverse if easy enough.

Surely we could write a channel mechanism that deals with:
http://packagist.org/packages.json

and code which parses a composer.json (https://github.com/fabpot/Pirum/blob/master/composer.json) to populate our model of a package / dependencies.

Why would we do it?
Composer.phar can be used on your local project. This is especially useful for CI. Though it is probably doable with pyrus.phar, but we're not yet doing it on test.pear.php.net:8080 - we use ant, an include_path and git clone or svn export to a lib/ dir.

At the moment, Pyrus/PEAR deal with the system wide installation case much better.

So...
As a pear/pyrus user; I'd very much like to be able to install a composer package system wide with existing tools. (php pyrus.phar channel-discover packagist.org)

As a pear developer, I'd like to be able to add dependencies to my package.xml for a composer only component (php pyrus.phar install packagist.org/foo/bar 1.0.0).

And in general - I'd like not to have to choose between to package ecosystems with only minimal differences in philosophy; but differences as to the code I can use without fuss.

**Comment by till** [comment]
We can revisit this when pyrus matures. Also, lol.
