### ISSUE TITLE
Improve the Error message thrown

### ISSUE THREAD

**Issue by harikt** [pyrus/Pyrus#82]
Recently I was having an issue downloading via Pyrus the Pear2\HTTP\Request 

Issue is over https://github.com/pear2/HTTP_Request/issues/4

```
 hari@hari-Vostro1510:/media/Linux/pyrus$ php pyrus.phar install PEAR2_HTTP_REQUEST
 Pyrus version 2.0.0a3 SHA-1: BE7EA9D171AE3873F1BBAF692EEE9165BB14BD5D
 Using PEAR installation found at /media/Linux/pyrus
 PEAR2\Pyrus\Installer\Exception: Dependency validation failed for some packages to install, installation aborted
  PEAR2\Pyrus\Package\Dependency\Set\Exception: Unable to find a compatible release for                            pear2.php.net/PEAR2_HTTP_Request
 hari@hari-Vostro1510:/media/Linux/pyrus$
```

But according to @saltybeagle , it was due to there are no releases which match

Good if its would have shown some improved message than this.

Thanks

Hari K T

**Comment by fpoirotte** [comment]
I believe this is the same as issue #14.

**Comment by harikt** [comment]
@fpoirotte Yes you are right . I just checked it . I am closing this then .
