### ISSUE TITLE
Pyrus\XMLParser\Exception: Cannot open phar:///.../built-in-commands.xml

### ISSUE THREAD

**Issue by johanneskonst** [pyrus/Pyrus#84]
I've tried to use the pyrus.phar from packages.zendframework.com, which gave me the following error:
Pyrus\XMLParser\Exception: Cannot open phar:///.../pyrus.phar/Pyrus_Pharer-0.1.0/data/pyrus.net/Pyrus/built-in-commands.xml for parsing.
So I tried the official pyrus.phar from pear2.php.net, which gave me a similar but slightly different error:
PEAR2\Pyrus\XMLParser\Exception: Cannot open phar:///.../pyrus.phar/PEAR2_Pyrus-2.0.0a3/data/pear2.php.net/PEAR2_Pyrus/built-in-commands.xml

$ php -v
PHP 5.3.8-ZS5.5.0 (cli) (built: Aug 23 2011 09:15:05) 
Copyright (c) 1997-2011 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2011 Zend Technologies
    with Zend Extension Manager v5.1, Copyright (c) 2003-2010, by Zend Technologies
    - with Zend Data Cache v4.0, Copyright (c) 2004-2010, by Zend Technologies [loaded] [licensed] [disabled]
    - with Zend Guard Loader v3.3, Copyright (c) 1998-2010, by Zend Technologies [loaded] [licensed] [enabled]
    - with Zend Download Server v1.5.0, Copyright (c) 1998-2010 Zend Technologies Ltd., by Zend Technologies [loaded] [licensed] [disabled]
    - with Zend Java Bridge v3.1, Copyright (c) 2004-2010, by Zend Technologies [loaded] [licensed] [enabled]
    - with Zend Job Queue v4.0, Copyright (c) 2004-2010, by Zend Technologies [loaded] [licensed] [enabled]
    - with Zend Session Clustering v4.0, Copyright (c) 2004-2010, by Zend Technologies [loaded] [licensed] [disabled]
    - with Zend Utils v1.0, Copyright (c) 2004-2010, by Zend Technologies [loaded] [licensed] [enabled]
    - with Zend Optimizer+ v4.1, Copyright (c) 1999-2010, by Zend Technologies [loaded] [licensed] [disabled]
    - with Zend Code Tracing v1.0, Copyright (c) 2009-2010, by Zend Technologies [loaded] [licensed] [enabled]
    - with Zend Monitor v4.1, Copyright (c) 1999-2010, by Zend Technologies [loaded] [licensed] [disabled]
    - with Zend Debugger v5.3, Copyright (c) 1999-2010, by Zend Technologies [loaded] [licensed] [enabled]
    - with Zend Page Cache v4.0, Copyright (c) 2004-2010, by Zend Technologies [loaded] [licensed] [disabled]

Have not tried to reproduce this on different systems yet.

**Comment by fpoirotte** [comment]
Could you please paste the exact command that resulted in this exception please? Having a simple way to reproduce the issue locally would greatly help.
Also, could you try to reproduce the issue with the current pyrus.phar archive at pear2.php.net? (Pyrus-2.0.0a4)

It seems the built-in-commands.xml file is indeed missing from both Pyrus-2.0.0a3 and Pyrus-2.0.0a4 (at least, that's what `phar.phar tree -f pyrus.phar | grep data` reports).

**Comment by johanneskonst** [comment]
Any command failed with above exception, even trying to execute the pyrus.phar without any extra args.
This might have been a PHP error though, as I'm unable to reproduce this with the original phar I used to get above exception with, as well as the fresh copy from pear2.php.net.
Current cli version:

```
PHP 5.3.9-ZS5.6.0 (cli) (built: Dec 22 2011 09:12:52) 
Copyright (c) 1997-2011 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2011 Zend Technologies
    with Zend Extension Manager v5.1, Copyright (c) 2003-2010, by Zend Technologies
    - with Zend Data Cache v4.0, Copyright (c) 2004-2010, by Zend Technologies [loaded] [licensed] [disabled]
    - with Zend Guard Loader v3.3, Copyright (c) 1998-2010, by Zend Technologies [loaded] [licensed] [enabled]
    - with Zend Download Server v1.5.0, Copyright (c) 1998-2010 Zend Technologies Ltd., by Zend Technologies [loaded] [licensed] [disabled]
    - with Zend Java Bridge v3.1, Copyright (c) 2004-2010, by Zend Technologies [loaded] [licensed] [enabled]
    - with Zend Job Queue v4.0, Copyright (c) 2004-2010, by Zend Technologies [loaded] [licensed] [enabled]
    - with Zend Session Clustering v4.0, Copyright (c) 2004-2010, by Zend Technologies [loaded] [licensed] [disabled]
    - with Zend Utils v1.0, Copyright (c) 2004-2010, by Zend Technologies [loaded] [licensed] [enabled]
    - with Zend Optimizer+ v4.1, Copyright (c) 1999-2010, by Zend Technologies [loaded] [licensed] [disabled]
    - with Zend Code Tracing v1.0, Copyright (c) 2009-2010, by Zend Technologies [loaded] [licensed] [enabled]
    - with Zend Monitor v4.1, Copyright (c) 1999-2010, by Zend Technologies [loaded] [licensed] [disabled]
    - with Zend Debugger v5.3, Copyright (c) 1999-2010, by Zend Technologies [loaded] [licensed] [enabled]
    - with Zend Page Cache v4.0, Copyright (c) 2004-2010, by Zend Technologies [loaded] [licensed] [disabled]
```
