### ISSUE TITLE
Exception when trying to create a release

### ISSUE THREAD

**Issue by harikt** [pyrus/Pyrus#87]
Following https://github.com/pyrus/Pyrus/blob/master/HOWTO-RELEASE

```
hari@hari-Vostro1510:/media/Linux/py/Pyrus$ php scripts/pyrus upgrade -p ../Pyrus_Developer/package.xml 
Using PEAR installation found at /media/Linux/pyrus
Downloading pyrus.net/Pyrus_Developer
Installed pyrus.net/Pyrus_Developer-0.5.0
hari@hari-Vostro1510:/media/Linux/py/Pyrus$ php -dphar.readonly=0 scripts/pyrus make -pphar,tar,tgz,zip
Using PEAR installation found at /media/Linux/pyrus
Unable to add all custom roles/tasks/commands: exception 'Pyrus\PluginRegistry\Exception' with message 'make is already mapped and cannot be re-used' in /media/Linux/py/Pyrus/src/Pyrus/PluginRegistry.php:112
Stack trace:
#0 /media/Linux/py/Pyrus/src/Pyrus/PluginRegistry.php(88): Pyrus\PluginRegistry::addCommand(Array)
#1 /media/Linux/py/Pyrus/src/Pyrus/ScriptFrontend/Commands.php(285): Pyrus\PluginRegistry->scan()
#2 /media/Linux/py/Pyrus/scripts/pyrus(53): Pyrus\ScriptFrontend\Commands->run(Array)
#3 {main}
Creating package.xml...done
Creating Pyrus-2.0.0a4.tgz
Creating Pyrus-2.0.0a4.tar
Creating Pyrus-2.0.0a4.phar
Creating Pyrus-2.0.0a4.zip
done
```

**Comment by saltybeagle** [comment]
It looks like you've got two 'make' commands mapped. If you're following the HOWTO-RELEASE file, step 1 recommends you install Pyrus_Developer — but these tools are already mapped using the local-developer-commands.xml file.

You can use one, or the other, but not both. Because commands must be unique, only the first one initialized will work. You can remove the Pyrus_Developer tools from your plugins registry if you prefer to use your local source copy.

**Comment by harikt** [comment]
@saltybeagle I followed https://github.com/pyrus/Pyrus/wiki/Developing-for-Pyrus , then followed the HOWTO-RELEASE file ,
I was not aware the first step was installing Pyrus_Developer .
From where can I remove it ? Where is the plugins registry :( . 
Currently its not creating the phar too :( , will it work , if the exception is gone ?

**Comment by saltybeagle** [comment]
I've packaged up an RC of 2.0.0a4 - see if it works for you

**Comment by harikt** [comment]
Hi @saltybeagle 

Thank you for making it available soon , but we have some other bug ? So opened another issue see 

https://github.com/pyrus/Pyrus/issues/94 

The package name is different when tar ball is created .
