### ISSUE TITLE
current Pyrus-2.0.0a4 not includes PEAR2\HTTP\Request correctly

### ISSUE THREAD

**Issue by sasezaki** [pyrus/Pyrus#93]
Hi. I've download Pyrus-2.0.0a4 from pear2.php.net.
But PEAR2_Http_Request seems to not include correctly.

```
$ php pyrus.phar install pear/FSM                                                          
Pyrus version 2.0.0a4 SHA-1: 19D26DFEFB88692813562BAE1673BDDFCB10FDED
Using PEAR installation found at ~/pyrus4
PHP Fatal error:  Class 'PEAR2\HTTP\Request' not found in phar:///home/sasezaki/pyrus.phar/Pyrus-2.0.0a4/php/Pyrus/Main.php on line 120
```

Extracted pyrus.phar 's directory structure (phar->extractTo()) is

```
$ ls Pyrus-2.0.0a4/php 
PEAR2  Pyrus  php
$ ls Pyrus-2.0.0a4/php/php
PEAR2
$ ls Pyrus-2.0.0a4/php/php/PEAR2
Exception.php  HTTP  MultiErrors  MultiErrors.php
```

**Comment by chilversc** [comment]
For reference, the full tree is https://gist.github.com/1876035

The directory in question is at line 37 https://gist.github.com/1876035#L37

**Comment by saltybeagle** [comment]
Thanks for the note! The bundled dependencies were apparently really messed up. Could you try the pyrus.phar I just committed?

https://github.com/pyrus/Pyrus/blob/master/pyrus.phar?raw=true

**Comment by sasezaki** [comment]
Fixed!Thanks!

**Comment by saltybeagle** [comment]
Great, sorry for the trouble.
