### ISSUE TITLE
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'Pyrus\PackageFile\v2' does not have a method 'hasConcreteVersion' in phar:///home/vagrant/.phpenv/versions/5.3.10/bin/pyrus.phar/Pyrus-2.0.0a4/php/Pyrus/Package/Base.p

### ISSUE THREAD

**Issue by CloCkWeRX** [pyrus/Pyrus#98]
See http://travis-ci.org/#!/CloCkWeRX/phpDocumentor2/jobs/937999

PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, class 'Pyrus\PackageFile\v2' does not have a method 'hasConcreteVersion' in phar:///home/vagrant/.phpenv/versions/5.3.10/bin/pyrus.phar/Pyrus-2.0.0a4/php/Pyrus/Package/Base.php on line 187

**Comment by lsolesen** [comment]
Also got this.

**Comment by till** [comment]
@CloCkWeRX This is merged, right?

**Comment by till** [comment]
Looked myself. Seems merged.
